### ISSUE TITLE
Wrong access modifiers (should be public) ?

### ISSUE THREAD

**Issue by ThePinion** [mhorod/oop-unit-tests#24]
https://github.com/mhorod/oop-unit-tests/blob/3029ea6f34f8b19767c4f0f1bf86d9f063337983/satori/F/MichalHorodeckiSmartFactoryTest.java#L368-L376

https://github.com/mhorod/oop-unit-tests/blob/3029ea6f34f8b19767c4f0f1bf86d9f063337983/satori/F/MichalHorodeckiSmartFactoryTest.java#L402-L405

**Comment by mhorod** [comment]
I think it shouldn't really matter because those fields are neither private nor protected so they should be accessible from the tests.
It's a good point though, I'll fix it soon.
